### ISSUE TITLE
If we need to consider the latency of memory model?

### ISSUE THREAD

**Issue by shirohasuki** [PrincetonUniversity/LLMCompass#2]
Hi, very AMAZING work! I like this. Thank you for your contributions.

There is one thing puzzling me. I've seen that both computation and io_module have latency in code, but I don't find latency of the memory model——like we **getting data from the loacl buffer(SRAM) or global buffer(HBM)** (not latency on link).

If you've already mentioned in your paper that I apologize for my omission.

Thanks!

**Comment by HenryChang213** [comment]
Global buffer is actually L2 cache in most of the cases. For these buffers, LLMCompass assumes only the latency of the first memory access is exposed. The following latency will be well hidden. What matters is bandwidth.

**Comment by HenryChang213** [comment]
We are working on a patch to incorporate memory access latency into the performance model, including DRAM latency and cache latency. The preliminary results currently look good.

**Comment by Zhaoyilunnn** [comment]
Hi @HenryChang213, thanks for the great work. I have some follow-up question in this thread.

- In the code, I noticed that the IO latency is calculated by `data_size / bandwidth + 2*latency` (in the [comment](https://github.com/PrincetonUniversity/LLMCompass/blob/62321b1ee28ddbdba8a2eb7475d7caa30f75e8be/software_model/matmul.py#L968-L970)), I am not sure I understand why the `latency` is considered twice.
- In the io module instance of HBM, the latency is set to be 1 microsecond, however, if I understand correctly, the latency of HBM is smaller than this, may be on the order of dozens of nanoseconds level.

Thanks in advance!
